export interface UniversityTheme {
  name: string;
  country: string;
  primaryColor: string;
  accentColor: string;
  textColor: string;
  acceptanceRate: string;
  knownFor: string[];
}

export const UNIVERSITY_THEMES: Record<string, UniversityTheme> = {
  // ── Ivy League ───────────────────────────────────────────────────────────────
  harvard: {
    name: 'Harvard University',
    country: 'United States',
    primaryColor: '#A51C30',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '3.4%',
    knownFor: ['Law', 'Business', 'Medicine', 'Political Science'],
  },
  yale: {
    name: 'Yale University',
    country: 'United States',
    primaryColor: '#00356B',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '4.6%',
    knownFor: ['Law', 'Drama', 'Economics', 'Political Science'],
  },
  princeton: {
    name: 'Princeton University',
    country: 'United States',
    primaryColor: '#FF6900',
    accentColor: '#1a1a1a',
    textColor: '#1a1a1a',
    acceptanceRate: '4.7%',
    knownFor: ['Mathematics', 'Physics', 'Public Policy', 'Economics'],
  },
  columbia: {
    name: 'Columbia University',
    country: 'United States',
    primaryColor: '#003087',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '3.9%',
    knownFor: ['Journalism', 'Business', 'Medicine', 'Engineering'],
  },
  penn: {
    name: 'University of Pennsylvania',
    country: 'United States',
    primaryColor: '#011F5B',
    accentColor: '#990000',
    textColor: '#fdfdfd',
    acceptanceRate: '5.9%',
    knownFor: ['Business (Wharton)', 'Medicine', 'Nursing', 'Engineering'],
  },
  brown: {
    name: 'Brown University',
    country: 'United States',
    primaryColor: '#4E3629',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '5.5%',
    knownFor: ['Open Curriculum', 'Neuroscience', 'Computer Science', 'Liberal Arts'],
  },
  dartmouth: {
    name: 'Dartmouth College',
    country: 'United States',
    primaryColor: '#00693E',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '6.3%',
    knownFor: ['Business (Tuck)', 'Engineering', 'Government', 'Liberal Arts'],
  },
  cornell: {
    name: 'Cornell University',
    country: 'United States',
    primaryColor: '#B31B1B',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '7.6%',
    knownFor: ['Engineering', 'Hotel Administration', 'Agriculture', 'Architecture'],
  },

  // ── Top US Universities ──────────────────────────────────────────────────────
  mit: {
    name: 'MIT',
    country: 'United States',
    primaryColor: '#750014',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '3.9%',
    knownFor: ['Engineering', 'Computer Science', 'Physics', 'Economics'],
  },
  stanford: {
    name: 'Stanford University',
    country: 'United States',
    primaryColor: '#8C1515',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '3.7%',
    knownFor: ['Computer Science', 'Engineering', 'Business', 'Medicine'],
  },
  caltech: {
    name: 'California Institute of Technology',
    country: 'United States',
    primaryColor: '#FF6C0C',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '3.9%',
    knownFor: ['Physics', 'Engineering', 'Chemistry', 'Astronomy'],
  },
  duke: {
    name: 'Duke University',
    country: 'United States',
    primaryColor: '#003087',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '6.5%',
    knownFor: ['Medicine', 'Law', 'Business', 'Public Policy'],
  },
  johns_hopkins: {
    name: 'Johns Hopkins University',
    country: 'United States',
    primaryColor: '#002D72',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '7.5%',
    knownFor: ['Medicine', 'Public Health', 'Engineering', 'International Studies'],
  },
  northwestern: {
    name: 'Northwestern University',
    country: 'United States',
    primaryColor: '#4E2A84',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '6.8%',
    knownFor: ['Journalism', 'Music', 'Engineering', 'Business (Kellogg)'],
  },
  vanderbilt: {
    name: 'Vanderbilt University',
    country: 'United States',
    primaryColor: '#866D4B',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '6.7%',
    knownFor: ['Medicine', 'Law', 'Music', 'Education'],
  },
  rice: {
    name: 'Rice University',
    country: 'United States',
    primaryColor: '#00205B',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '8.5%',
    knownFor: ['Engineering', 'Music', 'Architecture', 'Natural Sciences'],
  },
  notre_dame: {
    name: 'University of Notre Dame',
    country: 'United States',
    primaryColor: '#0C2340',
    accentColor: '#C99700',
    textColor: '#fdfdfd',
    acceptanceRate: '12.5%',
    knownFor: ['Law', 'Business', 'Engineering', 'Theology'],
  },
  georgetown: {
    name: 'Georgetown University',
    country: 'United States',
    primaryColor: '#041E42',
    accentColor: '#63808a',
    textColor: '#fdfdfd',
    acceptanceRate: '12%',
    knownFor: ['Foreign Service', 'Law', 'Business', 'Medicine'],
  },
  tufts: {
    name: 'Tufts University',
    country: 'United States',
    primaryColor: '#3E8EDE',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '11%',
    knownFor: ['International Relations', 'Engineering', 'Medicine', 'Liberal Arts'],
  },
  emory: {
    name: 'Emory University',
    country: 'United States',
    primaryColor: '#002878',
    accentColor: '#F2A900',
    textColor: '#fdfdfd',
    acceptanceRate: '11.6%',
    knownFor: ['Medicine', 'Law', 'Business', 'Public Health'],
  },
  cmu: {
    name: 'Carnegie Mellon University',
    country: 'United States',
    primaryColor: '#C41230',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '11%',
    knownFor: ['Computer Science', 'Robotics', 'Fine Arts', 'Engineering'],
  },
  uchicago: {
    name: 'University of Chicago',
    country: 'United States',
    primaryColor: '#800000',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '5.4%',
    knownFor: ['Economics', 'Law', 'Sociology', 'Political Science'],
  },
  washu: {
    name: 'Washington University in St. Louis',
    country: 'United States',
    primaryColor: '#A51417',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '11%',
    knownFor: ['Medicine', 'Business (Olin)', 'Engineering', 'Art'],
  },
  nyu: {
    name: 'New York University',
    country: 'United States',
    primaryColor: '#57068C',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '12.2%',
    knownFor: ['Business (Stern)', 'Law', 'Film', 'Liberal Arts'],
  },
  boston_university: {
    name: 'Boston University',
    country: 'United States',
    primaryColor: '#CC0000',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '18%',
    knownFor: ['Engineering', 'Business', 'Communications', 'Medicine'],
  },
  northeastern: {
    name: 'Northeastern University',
    country: 'United States',
    primaryColor: '#C8102E',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '6.7%',
    knownFor: ['Engineering', 'Computer Science', 'Business', 'Co-op Programs'],
  },
  carnegie_mellon: {
    name: 'Carnegie Mellon University',
    country: 'United States',
    primaryColor: '#A0000D',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '11%',
    knownFor: ['Computer Science', 'Robotics', 'AI', 'Fine Arts'],
  },
  georgia_tech: {
    name: 'Georgia Institute of Technology',
    country: 'United States',
    primaryColor: '#B3A369',
    accentColor: '#003057',
    textColor: '#fdfdfd',
    acceptanceRate: '17%',
    knownFor: ['Engineering', 'Computer Science', 'Analytics', 'Design'],
  },
  berkeley: {
    name: 'University of California, Berkeley',
    country: 'United States',
    primaryColor: '#003262',
    accentColor: '#FDB515',
    textColor: '#fdfdfd',
    acceptanceRate: '11%',
    knownFor: ['Computer Science', 'Engineering', 'Economics', 'Law'],
  },
  ucla: {
    name: 'University of California, Los Angeles',
    country: 'United States',
    primaryColor: '#2774AE',
    accentColor: '#FFD100',
    textColor: '#fdfdfd',
    acceptanceRate: '9%',
    knownFor: ['Medicine', 'Film', 'Engineering', 'Business'],
  },
  michigan: {
    name: 'University of Michigan',
    country: 'United States',
    primaryColor: '#00274C',
    accentColor: '#FFCB05',
    textColor: '#fdfdfd',
    acceptanceRate: '18%',
    knownFor: ['Engineering', 'Business', 'Medicine', 'Public Policy'],
  },
  carnegie: {
    name: 'University of California, San Diego',
    country: 'United States',
    primaryColor: '#005CAB',
    accentColor: '#C69214',
    textColor: '#fdfdfd',
    acceptanceRate: '24%',
    knownFor: ['Biology', 'Engineering', 'Oceanography', 'Computer Science'],
  },
  virginia: {
    name: 'University of Virginia',
    country: 'United States',
    primaryColor: '#232D4B',
    accentColor: '#E57200',
    textColor: '#fdfdfd',
    acceptanceRate: '19%',
    knownFor: ['Law', 'Business', 'Medicine', 'Public Policy'],
  },
  berkeley_haas: {
    name: 'University of California, Berkeley (Haas)',
    country: 'United States',
    primaryColor: '#003262',
    accentColor: '#FDB515',
    textColor: '#fdfdfd',
    acceptanceRate: '11%',
    knownFor: ['Business', 'Economics', 'Engineering', 'Data Science'],
  },
  texas: {
    name: 'University of Texas at Austin',
    country: 'United States',
    primaryColor: '#BF5700',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '29%',
    knownFor: ['Engineering', 'Business', 'Computer Science', 'Law'],
  },
  unc: {
    name: 'University of North Carolina at Chapel Hill',
    country: 'United States',
    primaryColor: '#7BAFD4',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '17%',
    knownFor: ['Journalism', 'Medicine', 'Business', 'Public Health'],
  },
  florida: {
    name: 'University of Florida',
    country: 'United States',
    primaryColor: '#0021A5',
    accentColor: '#FA4616',
    textColor: '#fdfdfd',
    acceptanceRate: '30%',
    knownFor: ['Engineering', 'Business', 'Medicine', 'Agriculture'],
  },
  purdue: {
    name: 'Purdue University',
    country: 'United States',
    primaryColor: '#CEB888',
    accentColor: '#000000',
    textColor: '#1a1a1a',
    acceptanceRate: '53%',
    knownFor: ['Engineering', 'Aviation', 'Computer Science', 'Agriculture'],
  },
  illinois: {
    name: 'University of Illinois Urbana-Champaign',
    country: 'United States',
    primaryColor: '#13294B',
    accentColor: '#E84A27',
    textColor: '#fdfdfd',
    acceptanceRate: '44%',
    knownFor: ['Engineering', 'Computer Science', 'Business', 'Agriculture'],
  },

  // ── UK Universities ──────────────────────────────────────────────────────────
  oxford: {
    name: 'University of Oxford',
    country: 'United Kingdom',
    primaryColor: '#002147',
    accentColor: '#C5903A',
    textColor: '#fdfdfd',
    acceptanceRate: '14.5%',
    knownFor: ['Philosophy', 'Medicine', 'Law', 'Politics'],
  },
  cambridge: {
    name: 'University of Cambridge',
    country: 'United Kingdom',
    primaryColor: '#003977',
    accentColor: '#C4AE6B',
    textColor: '#fdfdfd',
    acceptanceRate: '15%',
    knownFor: ['Mathematics', 'Natural Sciences', 'Engineering', 'Law'],
  },
  imperial: {
    name: 'Imperial College London',
    country: 'United Kingdom',
    primaryColor: '#003E74',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '14.3%',
    knownFor: ['Engineering', 'Medicine', 'Science', 'Business'],
  },
  ucl: {
    name: 'University College London',
    country: 'United Kingdom',
    primaryColor: '#500778',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '16.5%',
    knownFor: ['Medicine', 'Law', 'Engineering', 'Economics'],
  },
  lse: {
    name: 'London School of Economics',
    country: 'United Kingdom',
    primaryColor: '#D9291C',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '16%',
    knownFor: ['Economics', 'Political Science', 'Sociology', 'Law'],
  },
  edinburgh: {
    name: 'University of Edinburgh',
    country: 'United Kingdom',
    primaryColor: '#041E42',
    accentColor: '#C8A951',
    textColor: '#fdfdfd',
    acceptanceRate: '43%',
    knownFor: ['Medicine', 'Law', 'Engineering', 'Arts'],
  },
  kings_college: {
    name: "King's College London",
    country: 'United Kingdom',
    primaryColor: '#003D7A',
    accentColor: '#D4A017',
    textColor: '#fdfdfd',
    acceptanceRate: '13%',
    knownFor: ['Medicine', 'Law', 'International Relations', 'Humanities'],
  },
  manchester: {
    name: 'University of Manchester',
    country: 'United Kingdom',
    primaryColor: '#A10022',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '56%',
    knownFor: ['Engineering', 'Business', 'Medicine', 'Computer Science'],
  },
  warwick: {
    name: 'University of Warwick',
    country: 'United Kingdom',
    primaryColor: '#5B1F69',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '14%',
    knownFor: ['Economics', 'Business', 'Mathematics', 'Politics'],
  },
  bristol: {
    name: 'University of Bristol',
    country: 'United Kingdom',
    primaryColor: '#003B5C',
    accentColor: '#D0006F',
    textColor: '#fdfdfd',
    acceptanceRate: '67%',
    knownFor: ['Engineering', 'Medicine', 'Law', 'Sciences'],
  },
  durham: {
    name: 'Durham University',
    country: 'United Kingdom',
    primaryColor: '#562873',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '41%',
    knownFor: ['Law', 'Humanities', 'Physics', 'Business'],
  },
  bath: {
    name: 'University of Bath',
    country: 'United Kingdom',
    primaryColor: '#003865',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '10%',
    knownFor: ['Engineering', 'Architecture', 'Management', 'Computer Science'],
  },
  exeter: {
    name: 'University of Exeter',
    country: 'United Kingdom',
    primaryColor: '#0A4A7A',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '80%',
    knownFor: ['Business', 'Law', 'Environmental Science', 'Medicine'],
  },
  glasgow: {
    name: 'University of Glasgow',
    country: 'United Kingdom',
    primaryColor: '#003865',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '74%',
    knownFor: ['Medicine', 'Veterinary Medicine', 'Engineering', 'Arts'],
  },

  // ── South African Universities ───────────────────────────────────────────────
  uct: {
    name: 'University of Cape Town',
    country: 'South Africa',
    primaryColor: '#003B5C',
    accentColor: '#C9AC72',
    textColor: '#fdfdfd',
    acceptanceRate: '9%',
    knownFor: ['Medicine', 'Law', 'Engineering', 'Commerce'],
  },
  wits: {
    name: 'University of the Witwatersrand',
    country: 'South Africa',
    primaryColor: '#003D6B',
    accentColor: '#CC8800',
    textColor: '#fdfdfd',
    acceptanceRate: '15%',
    knownFor: ['Mining Engineering', 'Medicine', 'Business', 'Humanities'],
  },
  stellenbosch: {
    name: 'Stellenbosch University',
    country: 'South Africa',
    primaryColor: '#6B1F7C',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '40%',
    knownFor: ['Agriculture', 'Engineering', 'Business', 'Medicine'],
  },
  ukzn: {
    name: 'University of KwaZulu-Natal',
    country: 'South Africa',
    primaryColor: '#007749',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '35%',
    knownFor: ['Medicine', 'Engineering', 'Law', 'Agriculture'],
  },
  pretoria: {
    name: 'University of Pretoria',
    country: 'South Africa',
    primaryColor: '#00539F',
    accentColor: '#FFD100',
    textColor: '#fdfdfd',
    acceptanceRate: '25%',
    knownFor: ['Veterinary Science', 'Engineering', 'Law', 'Natural Sciences'],
  },
  rhodes: {
    name: 'Rhodes University',
    country: 'South Africa',
    primaryColor: '#003A63',
    accentColor: '#9C1F2E',
    textColor: '#fdfdfd',
    acceptanceRate: '74%',
    knownFor: ['Journalism', 'Humanities', 'Law', 'Science'],
  },
  unisa: {
    name: 'University of South Africa',
    country: 'South Africa',
    primaryColor: '#B31B1B',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: 'NA',
    knownFor: ['Distance Learning', 'Law', 'Education', 'Business'],
  },
  nelson_mandela: {
    name: 'Nelson Mandela University',
    country: 'South Africa',
    primaryColor: '#004A8F',
    accentColor: '#F3A712',
    textColor: '#fdfdfd',
    acceptanceRate: '60%',
    knownFor: ['Engineering', 'Business', 'Health Sciences', 'Architecture'],
  },
  university_of_free_state: {
    name: 'University of the Free State',
    country: 'South Africa',
    primaryColor: '#5B2C83',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '75%',
    knownFor: ['Health Sciences', 'Law', 'Humanities', 'Education'],
  },
  north_west: {
    name: 'North-West University',
    country: 'South Africa',
    primaryColor: '#8A1538',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '70%',
    knownFor: ['Education', 'Business', 'Engineering', 'Agriculture'],
  },

  // ── International Universities ───────────────────────────────────────────────
  eth_zurich: {
    name: 'ETH Zurich',
    country: 'Switzerland',
    primaryColor: '#1F407A',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '27%',
    knownFor: ['Engineering', 'Natural Sciences', 'Architecture', 'Computer Science'],
  },
  nus: {
    name: 'National University of Singapore',
    country: 'Singapore',
    primaryColor: '#003D7C',
    accentColor: '#EF7C00',
    textColor: '#fdfdfd',
    acceptanceRate: '5%',
    knownFor: ['Engineering', 'Business', 'Medicine', 'Law'],
  },
  toronto: {
    name: 'University of Toronto',
    country: 'Canada',
    primaryColor: '#002A5C',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '43%',
    knownFor: ['Medicine', 'Engineering', 'Humanities', 'Business'],
  },
  ubc: {
    name: 'University of British Columbia',
    country: 'Canada',
    primaryColor: '#002145',
    accentColor: '#B7C9D3',
    textColor: '#fdfdfd',
    acceptanceRate: '52%',
    knownFor: ['Medicine', 'Forestry', 'Business', 'Computer Science'],
  },
  mcgill: {
    name: 'McGill University',
    country: 'Canada',
    primaryColor: '#ED1B2F',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '46%',
    knownFor: ['Medicine', 'Law', 'Engineering', 'Music'],
  },
  melbourne: {
    name: 'University of Melbourne',
    country: 'Australia',
    primaryColor: '#003087',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '70%',
    knownFor: ['Medicine', 'Law', 'Engineering', 'Arts'],
  },
  anu: {
    name: 'Australian National University',
    country: 'Australia',
    primaryColor: '#1B4F8A',
    accentColor: '#FBAA17',
    textColor: '#fdfdfd',
    acceptanceRate: '35%',
    knownFor: ['Politics', 'Science', 'Law', 'International Relations'],
  },
  sydney: {
    name: 'University of Sydney',
    country: 'Australia',
    primaryColor: '#FFCD00',
    accentColor: '#0D223F',
    textColor: '#1a1a1a',
    acceptanceRate: '65%',
    knownFor: ['Medicine', 'Law', 'Engineering', 'Business'],
  },
  unsw: {
    name: 'University of New South Wales',
    country: 'Australia',
    primaryColor: '#0B4EA2',
    accentColor: '#F2A900',
    textColor: '#fdfdfd',
    acceptanceRate: '65%',
    knownFor: ['Engineering', 'Business', 'Computer Science', 'Medicine'],
  },
  monash: {
    name: 'Monash University',
    country: 'Australia',
    primaryColor: '#006DAE',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '40%',
    knownFor: ['Pharmacy', 'Medicine', 'Engineering', 'Business'],
  },
  queensland: {
    name: 'University of Queensland',
    country: 'Australia',
    primaryColor: '#51247A',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '40%',
    knownFor: ['Medicine', 'Engineering', 'Biotechnology', 'Business'],
  },
  adelaide: {
    name: 'University of Adelaide',
    country: 'Australia',
    primaryColor: '#8F003F',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '75%',
    knownFor: ['Medicine', 'Engineering', 'Agriculture', 'Law'],
  },
  western_australia: {
    name: 'University of Western Australia',
    country: 'Australia',
    primaryColor: '#203864',
    accentColor: '#FDB515',
    textColor: '#fdfdfd',
    acceptanceRate: '38%',
    knownFor: ['Marine Science', 'Engineering', 'Medicine', 'Business'],
  },

  // ── Europe Universities ───────────────────────────────────────────────────────
  ecole_polytechnique: {
    name: 'École Polytechnique',
    country: 'France',
    primaryColor: '#003A70',
    accentColor: '#C8102E',
    textColor: '#fdfdfd',
    acceptanceRate: '10%',
    knownFor: ['Mathematics', 'Engineering', 'Physics', 'Economics'],
  },
  sciences_po: {
    name: 'Sciences Po',
    country: 'France',
    primaryColor: '#004B87',
    accentColor: '#E4002B',
    textColor: '#fdfdfd',
    acceptanceRate: '17%',
    knownFor: ['Political Science', 'International Relations', 'Law', 'Economics'],
  },
  epfl: {
    name: 'EPFL',
    country: 'Switzerland',
    primaryColor: '#D52B1E',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '27%',
    knownFor: ['Engineering', 'Computer Science', 'Robotics', 'Architecture'],
  },
  st_andrews: {
    name: 'University of St Andrews',
    country: 'United Kingdom',
    primaryColor: '#8C1D40',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '8%',
    knownFor: ['International Relations', 'Philosophy', 'History', 'Sciences'],
  },
  heidelberg: {
    name: 'Heidelberg University',
    country: 'Germany',
    primaryColor: '#8A1538',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '17%',
    knownFor: ['Medicine', 'Law', 'Natural Sciences', 'Philosophy'],
  },
  munich: {
    name: 'Technical University of Munich',
    country: 'Germany',
    primaryColor: '#0065BD',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '8%',
    knownFor: ['Engineering', 'Computer Science', 'Robotics', 'Physics'],
  },
  trinity_dublin: {
    name: 'Trinity College Dublin',
    country: 'Ireland',
    primaryColor: '#00539B',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '33%',
    knownFor: ['Humanities', 'Law', 'Medicine', 'Computer Science'],
  },
  amsterdam: {
    name: 'University of Amsterdam',
    country: 'Netherlands',
    primaryColor: '#C00029',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '20%',
    knownFor: ['Economics', 'Law', 'Social Sciences', 'Media'],
  },
  leiden: {
    name: 'Leiden University',
    country: 'Netherlands',
    primaryColor: '#0066A1',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '36%',
    knownFor: ['Law', 'International Relations', 'Humanities', 'Medicine'],
  },
  copenhagen: {
    name: 'University of Copenhagen',
    country: 'Denmark',
    primaryColor: '#C8102E',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '36%',
    knownFor: ['Medicine', 'Natural Sciences', 'Law', 'Social Sciences'],
  },
  lund: {
    name: 'Lund University',
    country: 'Sweden',
    primaryColor: '#4F2C7F',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '34%',
    knownFor: ['Engineering', 'Medicine', 'Law', 'Business'],
  },
  oslo: {
    name: 'University of Oslo',
    country: 'Norway',
    primaryColor: '#00205B',
    accentColor: '#BA0C2F',
    textColor: '#fdfdfd',
    acceptanceRate: '30%',
    knownFor: ['Medicine', 'Law', 'Humanities', 'Sciences'],
  },
  eth_lausanne: {
    name: 'University of Lausanne',
    country: 'Switzerland',
    primaryColor: '#0055A4',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '33%',
    knownFor: ['Business', 'Law', 'Medicine', 'Social Sciences'],
  },
  polimi: {
    name: 'Politecnico di Milano',
    country: 'Italy',
    primaryColor: '#0063A6',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '12%',
    knownFor: ['Engineering', 'Architecture', 'Design', 'Computer Science'],
  },

  // ── Asia Universities ────────────────────────────────────────────────────────
  tsinghua: {
    name: 'Tsinghua University',
    country: 'China',
    primaryColor: '#7F0000',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '3%',
    knownFor: ['Engineering', 'Computer Science', 'Architecture', 'Economics'],
  },
  peking: {
    name: 'Peking University',
    country: 'China',
    primaryColor: '#8A1C1C',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '2%',
    knownFor: ['Law', 'Economics', 'Medicine', 'Humanities'],
  },
  hkust: {
    name: 'Hong Kong University of Science and Technology',
    country: 'Hong Kong',
    primaryColor: '#003C71',
    accentColor: '#A8A8A8',
    textColor: '#fdfdfd',
    acceptanceRate: '15%',
    knownFor: ['Engineering', 'Business', 'Computer Science', 'Science'],
  },
  tokyo: {
    name: 'University of Tokyo',
    country: 'Japan',
    primaryColor: '#8B0000',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '35%',
    knownFor: ['Law', 'Medicine', 'Engineering', 'Economics'],
  },
  kyoto: {
    name: 'Kyoto University',
    country: 'Japan',
    primaryColor: '#003366',
    accentColor: '#E5B43C',
    textColor: '#fdfdfd',
    acceptanceRate: '38%',
    knownFor: ['Science', 'Engineering', 'Medicine', 'Humanities'],
  },
  seoul_national: {
    name: 'Seoul National University',
    country: 'South Korea',
    primaryColor: '#003876',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '15%',
    knownFor: ['Medicine', 'Engineering', 'Law', 'Business'],
  },
  kaist: {
    name: 'KAIST',
    country: 'South Korea',
    primaryColor: '#005AA7',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '10%',
    knownFor: ['Engineering', 'Computer Science', 'Robotics', 'AI'],
  },
  ntu: {
    name: 'Nanyang Technological University',
    country: 'Singapore',
    primaryColor: '#D8232A',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '25%',
    knownFor: ['Engineering', 'Business', 'Science', 'Design'],
  },
  chulalongkorn: {
    name: 'Chulalongkorn University',
    country: 'Thailand',
    primaryColor: '#9D1C20',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '40%',
    knownFor: ['Medicine', 'Law', 'Engineering', 'Business'],
  },
  iit_delhi: {
    name: 'Indian Institute of Technology Delhi',
    country: 'India',
    primaryColor: '#1A4D8F',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '2%',
    knownFor: ['Engineering', 'Computer Science', 'Design', 'Research'],
  },
  iit_bombay: {
    name: 'Indian Institute of Technology Bombay',
    country: 'India',
    primaryColor: '#00529B',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '2%',
    knownFor: ['Engineering', 'Computer Science', 'Physics', 'Design'],
  },
  iisc: {
    name: 'Indian Institute of Science',
    country: 'India',
    primaryColor: '#003B5C',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '1%',
    knownFor: ['Research', 'Physics', 'Biology', 'Engineering'],
  },
  iit_madras: {
    name: 'Indian Institute of Technology Madras',
    country: 'India',
    primaryColor: '#8A1C7C',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '2%',
    knownFor: ['Engineering', 'Computer Science', 'Management', 'Research'],
  },
  hong_kong: {
    name: 'University of Hong Kong',
    country: 'Hong Kong',
    primaryColor: '#A67C00',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '17%',
    knownFor: ['Medicine', 'Law', 'Business', 'Engineering'],
  },
  fudan: {
    name: 'Fudan University',
    country: 'China',
    primaryColor: '#A50034',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '4%',
    knownFor: ['Medicine', 'Economics', 'International Relations', 'Science'],
  },
  sorbonne: {
    name: 'Sorbonne University',
    country: 'France',
    primaryColor: '#0055A4',
    accentColor: '#ffffff',
    textColor: '#fdfdfd',
    acceptanceRate: '10%',
    knownFor: ['Medicine', 'Humanities', 'Science', 'Engineering'],
  },

  // ── Default ──────────────────────────────────────────────────────────────────
  default: {
    name: 'General Academic',
    country: 'International',
    primaryColor: '#6366f1',
    accentColor: '#ffffff',
    textColor: '#ffffff',
    acceptanceRate: 'N/A',
    knownFor: ['All fields'],
  },
};
